version: '3.8'
services:
  devMail:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  postgreSQL:
    image: postgres
    ports:
      - 5432:5432
      - 49153:49153
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: ourdb
#    volumes:
#      - /home/linuxmachine/postgrestorage:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080