spring:
  datasource:
    #url: jdbc:postgresql://0.0.0.0:49153/ourdb
    url: jdbc:postgresql://0.0.0.0:5432/ourdb
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# ensure that after Hibernate schema creation is performed then additionally schema.sql is read for any additional schema changes and data.sql is executed to populate the database.
    defer-datasource-initialization: true
# script-based initialization is performed by default only for embedded databases, to always initialize a database using scripts
  sql.init.mode: always

  mvc:
    static-path-pattern: /content/**
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false

server:
  defaultImageName: dollar-gill-oKtRncpWNu0-unsplash.png
  error:
    whitelabel:
      enabled: false

jwt:
  secretKey: SuperLongAndVerySecureKey-[].~^+$&4
  tokenPrefix: 'Bearer '
  tokenExpirationAfterMilliseconds: 25200000
  refreshTokenExpirationAfterDays: 7

# GMAIL
#mail:
#  username: ${USERNAME:yourGmailName@gmail.com}
#  password: ${PASSWORD:yourGmailPassword}
#  simpleMailTransferProtocol: smtps
#  fromEmail: support@example.com
#  ccEmail: ''
#  mailSubject: 'Application Name'
#  gmailSmtpServer: smtp.gmail.com
#  smtpHost: mail.smtp.host
#  smtpAuth: mail.smtp.auth
#  smtpPort: mail.smtp.port
#  defaultPort: 465
#  smtpStartTLSEnable: mail.smtp.starttls.enable
#  smtpStartTLSRequired: mail.smtp.starttls.required

#MAILDEV
mail:
  username: ${USERNAME:yourGmailName@gmail.com}
  password: ${PASSWORD:yourGmailPassword}
  simpleMailTransferProtocol: smtp
  fromEmail: support@example.com
  ccEmail: ''
  mailSubject: 'Application Name'
  gmailSmtpServer: localhost
  smtpHost: mail.smtp.host
  smtpAuth: mail.smtp.auth
  smtpPort: mail.smtp.port
  defaultPort: 1025
  smtpStartTLSEnable: mail.smtp.starttls.enable
  smtpStartTLSRequired: mail.smtp.starttls.required

base_reset_url: http://localhost:4200/restorePassword?code=
base_user_image_url: http://localhost:8080/users/image/
